"""
Django settings for galleries project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'smx!ez*lr=hr7h_%2wav2=8^)a5n-^svfsl1k0@a@(!k8(8ilk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'sa_helper',
    'albums',
    'galleries',
    'django.contrib.staticfiles',
    'rest_framework',
]

REST_FRAMEWORK = {
    # Cause we removing authentication entirely
    'UNAUTHENTICATED_USER': None,
}


MIDDLEWARE = [
]


SESSION_ENGINE = 'django.contrib.sessions.backends.file'

ROOT_URLCONF = 'galleries.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'galleries.wsgi.application'


SA_DATABASE_URL = 'sqlite:///foo.db'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/medial/'

SITE_URL_IN_EMAIL = 'https://mysite.com'
NEW_PHOTO_FROM_EMAIL = 'uploads@mysite.com'

CELERY_BROKER_URL = 'amqp://guest:guest@localhost//'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

THUMBNAIL_SIZES = {
    'middle': (1024, 768),
    'small': (300, 200)
}
