version: '3'
services:
  web:
    build:
      context: .
      dockerfile: galleries_app/Dockerfile
    ports:
     - "8000:8000"
    expose:
     - "8000"
    depends_on:
     - postgres
     - rabbitmq
    volumes:
     - media:/app/media
     - sessions:/app/sessions

  catalogues:
    build:
      context: .
      dockerfile: catalogues_app/Dockerfile
    ports:
     - "8001:8001"
    expose:
     - "8001"
    depends_on:
     - postgres

  celery:
    build:
      context: .
      dockerfile: galleries_app/Dockerfile
    command: celery -A galleries worker -l info
    depends_on:
      - postgres
      - rabbitmq
      - web
    volumes:
     - media:/app/media

  rabbitmq:
    image: "rabbitmq:alpine"

  postgres:
    image: "postgres:alpine"

  memcached:
    image: "memcached:alpine"

volumes:
  media:
  sessions:
